### ISSUE TITLE
`i3nator start todo` doen't open all the windows and the applications I want. 

### ISSUE THREAD

**Issue by oren** [pitkley/i3nator#186]
I have a project that has 3 terminals. one on the left and 2 and the right. One with `vim src/*.ts`, another one with `npm start`, and third one is `cd build && ./app.js`.

I generated a layout with the `i3-save-tree`.

cat /home/oren/.config/i3nator/projects/todo.toml

```
[general]
working_directory = "/home/oren/p/todo"
workspace = "3"
layout = "todolayout"

[[applications]]
command = "alacritty"
exec = ["cd /home/oren/p", "vim src/app.ts"]
```

cat /home/oren/.config/i3nator/layouts/todolayout.toml
```
// vim:ts=4:sw=4:et
{
    "border": "pixel",
    "current_border_width": 1,
    "floating": "auto_off",
    "geometry": {
       "height": 600,
       "width": 800,
       "x": 0,
       "y": 0
    },
    "marks": [],
    "name": "Alacritty",
    "percent": 0.333333333333333,
    "swallows": [
       {
       // "class": "^Alacritty$",
       // "instance": "^Alacritty$",
       // "machine": "^oren$",
       // "title": "^Alacritty$"
       }
    ],
    "type": "con"
}

{
    // splitv split container with 1 children
    "border": "pixel",
    "floating": "auto_off",
    "layout": "splitv",
    "marks": [],
    "percent": 0.333333333333333,
    "type": "con",
    "nodes": [
        {
            "border": "pixel",
            "current_border_width": 1,
            "floating": "auto_off",
            "geometry": {
               "height": 600,
               "width": 800,
               "x": 0,
               "y": 0
            },
            "marks": [],
            "name": "Alacritty",
            "percent": 1,
            "swallows": [
               {
               // "class": "^Alacritty$",
               // "instance": "^Alacritty$",
               // "machine": "^oren$",
               // "title": "^Alacritty$"
               }
            ],
            "type": "con"
        }
    ]
}

{
    // splitv split container with 2 children
    "border": "pixel",
    "floating": "auto_off",
    "layout": "splitv",
    "marks": [],
    "percent": 0.333333333333333,
    "type": "con",
    "nodes": [
        {
            "border": "pixel",
            "current_border_width": 1,
            "floating": "auto_off",
            "geometry": {
               "height": 600,
               "width": 800,
               "x": 0,
               "y": 0
            },
            "marks": [],
            "name": "Alacritty",
            "percent": 0.5,
            "swallows": [
               {
               // "class": "^Alacritty$",
               // "instance": "^Alacritty$",
               // "machine": "^oren$",
               // "title": "^Alacritty$"
               }
            ],
            "type": "con"
        },
        {
            "border": "pixel",
            "current_border_width": 1,
            "floating": "auto_off",
            "geometry": {
               "height": 600,
               "width": 800,
               "x": 0,
               "y": 0
            },
            "marks": [],
            "name": "Alacritty",
            "percent": 0.5,
            "swallows": [
               {
               // "class": "^Alacritty$",
               // "instance": "^Alacritty$",
               // "machine": "^oren$",
               // "title": "^Alacritty$"
               }
            ],
            "type": "con"
        }
    ]
}
```

**Comment by pitkley** [comment]
Hi @oren, thanks for reaching out. One thing I immediately notice: your `todo.toml` only contains a single application to be launched, one instance of Alacritty. If you only start one application, the i3 layout can only consume one window, leaving the other two empty.

Given what you have described, you'd likely want something closer to this:

```toml
[general]
working_directory = "/home/oren/p/todo"
workspace = "3"
layout = "todolayout"

[[applications]]
command = "alacritty"
exec = ["cd /home/oren/p", "vim src/app.ts"]

[[applications]]
command = "alacritty"
exec = ["cd /home/oren/p", "npm start"]

[[applications]]
command = "alacritty"
exec = ["cd /home/oren/p", "cd build && ./app.js"]
```

One issue that you will experience with this on its own is that i3 will not be able to tell which terminal should go in which of the placeholders created when launching the project. One easy way to fix this is to launch the three Alacritty terminals with different titles:

```toml
[[applications]]
command = "alacritty --title todo-vim"
exec = ["cd /home/oren/p", "vim src/app.ts"]

[[applications]]
command = "alacritty --title todo-npm-start"
exec = ["cd /home/oren/p", "npm start"]

[[applications]]
command = "alacritty --title todo-run-app"
exec = ["cd /home/oren/p", "cd build && ./app.js"]
```

You can then use these title's in the `swallows` configuration of the i3 layout, with something like this:

```json
{
  // ...
  "swallows": [
     {
       "class": "^Alacritty$",
       "title": "todo-vim"
     }
  ],
  // ...
}
